### ISSUE TITLE
sql Interface possibly vulnerable

### ISSUE THREAD

**Issue by sanvero** [maalurprograms/PHP-Blog#2]
Der Code sollte so nicht in einer Produktiv Umgebung eingesetzt werden.
Durch die direkte Übernahme von Usereingaben, die immer als gefährlich eingestuft werden sollten, in die sql query besteht die Gefahr von sql-injections.

Die Datenbank über pdo anzusteuern und prepared statements zu verwenden halte ich für sinnvoller.
Das Repository scheint ja (seit 3 Jahren) nicht weiter entwickelt zu werden. Wollte es nur erwähnt haben.

**Comment by velrest** [comment]
Danke für die Info aber dies war ein Schulprojekt und als solches nie für einen produktiven Einstatz geplant. Ausserdem wurde es mit minimalstem Aufwand erstellt.
